Isolate from logger
fullstack-development/haskell-starter-kit pull request #30
Opened 2021-04-12 15:03 UTC by antonkalinin-ml

Сделал тайпкласс `MonadLogger`, задуманный как интерфейс логгера, независимый от конкретной реализации. Спрятал все обращения к `colog` за ним. Далее я буду заменять `colog` на `katip`, что будет значительно легче с новым интерфейсом.

2021-04-13 11:07 UTC, kelizarov requested changes

2021-04-13 11:07 UTC, kelizarov commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Я бы лучше оставил префикс `log*` для названий функции, чтобы не было коллизии с функциями из base.

2021-04-13 11:07 UTC, kelizarov commented on src/Ext/Logger.hs
> +warn = GHC.withFrozenCallStack $logCapturingCallStack Warning
Тут немного форматтинг сбился.

2021-04-13 12:27 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Тогда будет дублирование слова `log` - `Log.logInfo`. Этот модуль удобно использовать с квалифицированным импортом, под это я его и делал.

2021-04-13 12:28 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Иногда об этом пишут в комменте к модулю, мол, сделано для квалифицированного импорта. Напишу (хотя не факт, что прочитают, но это другой вопрос).

2021-04-13 12:36 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +warn = GHC.withFrozenCallStack $logCapturingCallStack Warning
Вот тебе и пайплайн с проверкой формата :(

2021-04-13 13:10 UTC, kelizarov commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Я думаю лучше не применять такую практику, чтобы всегда этот модуль квалифайд импортили. Это уже становится как некое доп. соглашение, чего лично я бы хотел бы избежать в апи модуля :)

2021-04-14 07:19 UTC, olegromashin commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Плюсую Кириллу. Мне ещё не нравится, что без префикса складывается впечатление, что это переменная, а не функция. Например, debug вообще непонятно, да и про info я бы подумал, что там хранится какое-то сообщение. Такое сложнее читать.

2021-04-14 09:16 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Ок, добавлю префикс. В самом деле, одинокий `debug` выглядит загадочно.

> Я думаю лучше не применять такую практику, чтобы всегда этот модуль квалифайд импортили. Это уже становится как некое доп. соглашение, чего лично я бы хотел бы избежать в апи модуля :)

А нужен ли этот выбор, как импортировать модуль? `logInfo` мало отличается от `Log.info` в количестве введенных символов, зато появляется гибкость - можно сделать длинный и понятный псевдоним модуля, можно короткий, если очень часто используется. Имена в модуле становятся короче, они не обязаны содержать слово logger. Я так понял, вариантов импортов разрешено два: qualified import и unqualified import со списком импорта. Второй вариант мне очень не нравится многословностью, возней по добавлению-удалению имен в эти списки, отвлечением внимания во время набора кода - редактор ругается на неизвестное имя или на неиспользуемый импорт. Я его использую редко, только для импорта операторов или всем известных имен из `base`. После опыта в других языках непонятно, почему в хаскеле принято водить такие хороводы вокруг списков импортов :). Во многих языках их вообще нет, и никаких проблем по этому поводу люди не испытывают.

Например, в кодовой базе GHC [не рекомендуется использовать списки импорта](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/coding-style#imports):

> **Do not use explicit import lists**, except to resolve name clashes.  There are several reasons for this:
> - They slow down development: almost every change is accompanied by an import list change.
> - They cause spurious conflicts between developers.
> - They lead to useless warnings about unused imports, and time wasted trying to
keep the import declarations "minimal".
> - GHC's warnings are useful for detecting unnecessary imports: see -fwarn-unused-imports.
> - TAGS is a good way to find out where an identifier is defined (use hasktags or a similar program in ghc/compiler to generate TAGS file,
and hit M-. in Emacs; see here for details).

Я где-то читал рекомендации разрабатывать модули под квалифицированный импорт, чтобы вызовы выглядели `HashMap.insert`, а не `insertHM` или `insertHashMap`.

То, что якобы списки импорта улучшают читабельность - никогда этого не понимал. В vscode и емаксе есть go to definition, который мгновенно показывает код нужной функции (только на либах не работает). Это гораздо удобнее, чем скроллить до заголовка модуля и разыскивать глазами, что откуда импортируется, а потом руками открывать нужный модуль и искать нужную функцию.

2021-04-15 15:04 UTC, Znack commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Ну вообще я сейчас тоже всё больше склоняюсь к тому, что квалифицированные импорты удобней. По крайней мере пока они короткие, такие как `Log`. Когда же имена становятся `OperationDayScheduledTransactionWhateverYouWantToAddHere`, то начинается боль :)

2021-04-15 15:05 UTC, Znack commented
Эх, ещё недавно в душе у меня была надежда вмержить нам в проект обновления из стартеркита, но после этого апдейта, у нас будет столько конфликтов, что проще руками остальные изменения перенести 😆

2021-04-19 17:19 UTC, stanislav-az commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Плюсую за то что слова `debug`, `info`, `warn`, `error` не понятные (даже с квалифицированными импортами я бы ожидал другого поведения). Мне нравится` Log.logError`, по-моему повторение здесь не бесит и не удлиняет особо.

2021-04-19 17:19 UTC, stanislav-az commented on src/Ext/Logger/Colog.hs
> +newtype LoggerT m a = LoggerT {runLoggerT :: Colog.LoggerT Colog.Message m a}
А зачем дополнительную обертку делать чтобы один раз ее развернуть? В принципе, не мешает конечно, но спутать легко в другом модуле этот `LoggerT` и `Colog.LoggerT`

2021-04-19 19:15 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +error = GHC.withFrozenCallStack $ logCapturingCallStack Error
Поправил.

2021-04-19 19:27 UTC, antonkalinin-ml commented on src/Ext/Logger/Colog.hs
> +newtype LoggerT m a = LoggerT {runLoggerT :: Colog.LoggerT Colog.Message m a}
Чтобы вся настройка colog выполнялась только в этом модуле, а внешний код знал о нем как можно меньше и мог только выполнить ограниченный набор операций - `runWithAction`. Чтобы сделать API для запуска логгера, удобное и конфигурабельное для нас, а не для автора colog. Писать короче `LoggerT`, а не `LoggerT Message и еще куча всего`. Соглашусь, что возможна некая путаница в именах, но как еще назвать этот тип, если не `LoggerT` - это монадный трансформер с добавлением функциональности логгера, самое логичное имя. У colog нет монополии на имя `LoggerT`, оно не только в нем встречается. Данный модуль импортируется только как qualified, так что сложно перепутать.

2021-04-19 19:31 UTC, antonkalinin-ml commented on src/Ext/Logger/Colog.hs
> +newtype LoggerT m a = LoggerT {runLoggerT :: Colog.LoggerT Colog.Message m a}
Изоляция от colog неполная, некоторые модули все равно импортируют colog. Я просто не доделал рефакторинг, смысла нет, если мы все равно заменяем на другой логгер.

2021-04-19 19:38 UTC, antonkalinin-ml commented
> Эх, ещё недавно в душе у меня была надежда вмержить нам в проект обновления из стартеркита, но после этого апдейта, у нас будет столько конфликтов, что проще руками остальные изменения перенести laughing

Ну и смержим, API логгера не поменялось особо. Я вернул на место `logInfo` & co. Много конфликтов в импортах придется разгребать, но это мелочь. Только мне кажется, что нет смысла заменять логгер в прототипе :).

2021-04-20 05:04 UTC, stanislav-az approved these changes

2021-04-20 05:14 UTC, antonkalinin-ml commented on src/Ext/Logger/Colog.hs
> +newtype LoggerT m a = LoggerT {runLoggerT :: Colog.LoggerT Colog.Message m a}
Самое главное забыл - `LoggerT` нужен, чтобы сделать инстанс `MonadLogger` без варнинга об orphan instance.

2021-05-11 07:21 UTC, olegromashin approved these changes

2021-05-19 08:12 UTC, Znack commented on src/Ext/Logger.hs
> +newtype CallStack = CallStack {unCallStack :: GHC.CallStack}
а зачем своя обертка над коллстеком?

2021-05-19 08:12 UTC, Znack approved these changes

2021-05-19 08:30 UTC, antonkalinin-ml commented on src/Ext/Logger.hs
> +newtype CallStack = CallStack {unCallStack :: GHC.CallStack}
Это абстрактная информации о месте вызова. Сначала я тут хотел передавать только строку, функцию и файл, но этого недостаточно, имя вызывающей функции не выведется. И раз уж colog умеет выводить стек, пускай будет стек, пригодится.

У GHC есть несколько механизмов для коллстеков (GHC.Callstack, стек профилировщика), их можно менять. Юзеру нежелательно видеть точный механизм, он сам не создает коллстек. Это делает logInfo & co.

2021-05-19 08:37 UTC, Znack commented on src/Ext/Logger.hs
> +newtype CallStack = CallStack {unCallStack :: GHC.CallStack}
Ага, понял, звучит логично :)

2021-09-05 11:58 UTC, antonkalinin-ml commented
Уже неактуально

2021-09-05 13:10 UTC, Znack commented
А почему кстати неактуально? я если честно просто забыл про ПР :) не знаю почему не вмержили

2021-09-05 13:51 UTC, antonkalinin-ml commented
В другом проекте мы это уже сделали, а здесь рефакторинг затевали ради переезда на katip, но теперь непонятно, будет ли он. Работы по стартеркиту не ведутся.

2021-09-05 14:08 UTC, Znack commented
Ну они не ведутся временно, но это не значит что мы его забросили :) Как появится у кого нибудь время, возобновим, и уже хорошо будет если к тому времени логгер будут проапргейден твоим этим ПРом :)

2021-09-05 14:11 UTC, antonkalinin-ml commented
Воскресил

2021-09-05 14:32 UTC, Znack commented
@kelizarov тебя ждём получается :)

![image](https://user-images.githubusercontent.com/2928964/132130645-0846dc25-6ed5-4f39-a861-61cb45019add.png)

2021-09-07 12:28 UTC, kelizarov approved these changes

2021-09-07 12:28 UTC, merged